name: ci-build-push

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: ap-south-1
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pytest -q

    - name: Security Scan (Trivy)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: "localbuild/test:latest"
        scan-type: "fs"
        severity: "CRITICAL,HIGH"

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActionsOIDCRole
        aws-region: ap-south-1

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      run: |
        IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/sample-fastapi:${{ github.sha }}"
        docker build -t "$IMAGE" .
        docker push "$IMAGE"
